fix(tianmu): fix query with ESCAPE (#271 #272)
stoneatom/stonedb pull request #1002
Opened 2022-11-24 12:14 UTC by adofsauron

Reasons: The escape character is not properly passed to the tianmu blur match handler

## Summary about this PR

Issue Number: close #271 #272 #273 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-11-24 12:17 UTC, RingsC requested changes

2022-11-24 12:17 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue271.test
> +SELECT * FROM test1 WHERE a LIKE 'hakan\%' ESCAPE '*';
adding some test cases for unicode chars.

2022-11-25 01:43 UTC, RingsC approved these changes
LGTM

2022-11-25 01:45 UTC, lujiashun approved these changes
LGTM

2022-11-25 01:46 UTC, merged