feat(tianmu): To support Binlog in mandatory tianmu engine mode (#956)
stoneatom/stonedb pull request #1005
Opened 2022-11-25 06:02 UTC by konghaiya

The function of forcing the replacement engine to be tianmu only takes effect in the slave library Step 1: First, you need to determine whether it is a slave database. This can be determined by whether (thread ->slave_thread) is true According to the configuration of forced replacement: (sql_mode='MANDATORY_TIANMU ') and (default_storage_engine=tianmu) Step 2: Determine whether the (sql_mode) and default engine are tianmu, and add (MANDATORY_TIANMU) this (sql_mode) The above conditions can be judged in (mysql_execute_command)

## Summary about this PR

Issue Number: close #956

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-11-28 02:14 UTC, RingsC requested changes

2022-11-28 02:14 UTC, RingsC commented on mysql-test/suite/tianmu/r/issue819.result
> +place_id int (10),
You should be aware of data type, you have changed from `unsigned` int to `int`. and should wirte it back when you are ready.

2022-11-28 09:04 UTC, konghaiya commented on mysql-test/suite/tianmu/r/issue819.result
> +place_id int (10),
Yes, it is necessary to add this test case in the future

2022-11-29 13:25 UTC, RingsC requested changes

2022-11-29 13:25 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue956.test
> +--disable_warnings
```
--include/have_binlog_format_row.inc
```

2022-11-29 13:25 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue956.test
> +stop slave;
```
--source include/rpl_end.inc
```

2022-11-29 13:25 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue956.test
> +--echo # connection master
```
--echo [on master]
connection master;
```

2022-11-29 13:25 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue956.test
> +--echo # connection master
```
--echo [on slave]
connection slave;
```

2022-11-29 13:25 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue956.test
> +sleep 1;
why this?
```
sleep 1;
```

2022-11-30 03:27 UTC, konghaiya commented on mysql-test/suite/tianmu/t/issue956.test
> +--disable_warnings
added

2022-11-30 03:27 UTC, konghaiya commented on mysql-test/suite/tianmu/t/issue956.test
> +--echo # connection master
Modified

2022-11-30 03:28 UTC, konghaiya commented on mysql-test/suite/tianmu/t/issue956.test
> +sleep 1;
Debug code, deleted

2022-11-30 03:30 UTC, konghaiya commented on mysql-test/suite/tianmu/t/issue956.test
> +stop slave;
The usage is not clear, and there is already (stop slave;) Used to end a dependent process

2022-11-30 06:26 UTC, RingsC approved these changes
LGTM

2022-11-30 06:30 UTC, lujiashun approved these changes
LGTM

2022-11-30 07:07 UTC, merged