ix(tianmu): fix Update multiple values does not work (#781)
stoneatom/stonedb pull request #1094
Opened 2022-12-08 06:36 UTC by adofsauron

Cause of error:
        Update multiple values does not work with WHERE IN
        clause Update multiple values does not work with where in clause.
        Predicate push-down from TIANMU is used, and this process works fine.
        But when you get the direct result,
        it is not compatible with TIANMU's dimen_group concrete type.
        In the execution of a predicate push-down,
        must get the Filter so that the execution of the follow-up to value,
        namely DimensionGroupFilter,
        but the current statement USES the materialized DimensionGroupMaterialized operation

    Solution Strategy:
        If the query is executed by a predicate pushdown, materialization is not enabled

    What remains:
        When no materialization operation is used in predicate push-down,
        the impact on query performance of predicate push-down
        needs to be cross-checked against benchmarks

## Summary about this PR

Issue Number: close #781 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-12-08 08:23 UTC, RingsC requested changes

2022-12-08 08:23 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue781.test
> +CREATE TABLE cs1 (d1 int, d2 int) ENGINE=TIANMU;
how about the filter is on PK. For example:

create table tb1 (d1 int primary key, d2 int) engine =tianmu;

select xxxx from tb1 where d1 in (xxx);

2022-12-08 08:23 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue781.test
> +UPDATE cs1 SET d1=888, d2=777 WHERE d1 in (125, 99999);
adds cases for `not in`.

2022-12-08 08:34 UTC, RingsC requested changes

2022-12-08 08:34 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue781.test
> +UPDATE cs1 SET d1=888, d2=777 WHERE d1 in (99998);
How about the `exists` clause. The optimization of `exists`  is same as `in` statement in mysql.

2022-12-08 08:34 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue781.test
> +SELECT * FROM cs1;
Adds a case for `json` type. Due to the json is a type used to stored array data in mysql. Now that, the json is not supported by Tianmu. 

create table tb (c1 json, c2 int) engine =tianmu;

2022-12-09 07:58 UTC, RingsC requested changes

2022-12-09 07:58 UTC, RingsC commented on storage/tianmu/core/temp_table.h
> +  void MarkCondPush() { occur_cond_push = true; };
The function name is not a better choice.
```
void SetCondPushDown() {}
bool CanCondPushDown() {}
```

2022-12-09 07:58 UTC, RingsC commented on storage/tianmu/core/temp_table.h
> +  bool occur_cond_push = false;  // Conditional push occurs
using
`
bool can_cond_push_down = false; 
`

2022-12-09 07:58 UTC, RingsC commented on storage/tianmu/core/query.h
> +                         bool is_or_subtree = false, bool is_cond_push = false);
```
bool can_cond_push_down
```

2022-12-09 07:58 UTC, RingsC commented on storage/tianmu/core/query.cpp
> +                                                  CondID *and_me_filter, bool is_or_subtree, bool is_cond_push) {
prefer `can_cond_push_down`

2022-12-09 09:03 UTC, RingsC approved these changes

2022-12-09 10:02 UTC, haitaoguan approved these changes

2022-12-09 10:12 UTC, merged