support exists/in subquery convert to semi-join (#864)
stoneatom/stonedb pull request #1322
Opened 2023-02-22 07:52 UTC by duanfuxiang0

## Summary about this PR

Issue Number: close #864 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [x] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2023-02-22 08:04 UTC, isredstar approved these changes

2023-02-22 08:05 UTC, hustjieke requested changes
Please do a rebase, the same commit msg is too much

2023-02-22 08:05 UTC, konghaiya approved these changes
LGTM

2023-02-23 09:28 UTC, RingsC commented
> ## Summary about this PR
> Issue Number: close #864
> 
> ## Tests Check List
> * [ ]  Unit test
> * [ ]  Integration test
> * [x]  Manual test (add detailed scripts or steps below)
> * [ ]  No code
> 
> ## Changelog
> * [ ]  New Feature
> * [ ]  Bug Fix
> * [x]  Performance Improvement
> * [ ]  Build/Testing/CI/CD
> * [ ]  Documentation
> * [ ]  Not for changelog (changelog entry is not required)
> 
> ## Documentation
> * [ ]  Affects user behaviors
> * [ ]  Contains syntax changes
> * [ ]  Contains variable changes
> * [ ]  Contains experimental features

@duanfuxiang0 pls, give more summary info on this PR.

2023-02-23 10:41 UTC, RingsC requested changes

2023-02-23 10:41 UTC, RingsC commented on mysql-test/suite/tianmu/r/issue947.result
> -1
@davidshiz , pls check out this MTRs. Make sure why we change the test result.

2023-02-23 10:41 UTC, RingsC commented on mysql-test/suite/tianmu/r/semi-join.result
> +SELECT t1_int, count(*) FROM t1 WHERE EXISTS (SELECT t2_int FROM t2 WHERE t1.t1_int = t2.t2_int) GROUP BY t1_int;
Add you add tests to display the query plan.  therefore, we can identify whether semi-join takes into effect

2023-02-23 10:41 UTC, RingsC commented on mysql-test/suite/tianmu/r/semi-join.result
> +t1_int
@davidshiz ,pls give us more complex query tests for `in/exists` statement. Thanks

2023-02-23 11:18 UTC, davidshiz commented on mysql-test/suite/tianmu/r/issue947.result
> -1
ok

2023-02-23 11:33 UTC, davidshiz commented on mysql-test/suite/tianmu/r/issue947.result
> -1
after verification, the issue947.result was wrong before, it is correct now @RingsC @duanfuxiang0

2023-02-27 01:54 UTC, wisehead approved these changes

2023-03-10 08:12 UTC, closed without merging