fix(tianmu): fix endless loop occurs during data_cache (#1352)
stoneatom/stonedb pull request #1353
Opened 2023-03-03 09:35 UTC by adofsauron

1. The CACHE_ITEM type does not recurse by making a direct comparison
    2. When two referenced variables have the same address,
        they are considered to be the same value

## Summary about this PR

Issue Number: close #1352 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2023-03-03 13:55 UTC, RingsC requested changes

2023-03-03 13:55 UTC, RingsC commented on mysql-test/suite/tianmu/r/issue1352.result
> +insert test values(now());
adds some tests for deterministic-volatile function.
F.Y.I: https://stackoverflow.com/questions/70088382/deterministic-volatile-function-in-sql

2023-03-05 07:24 UTC, RingsC approved these changes

2023-03-05 08:56 UTC, hustjieke approved these changes
LGTM

2023-03-06 01:33 UTC, wisehead approved these changes

2023-03-06 01:51 UTC, merged