fix(tianmu): mysqld crash when exec query limit 0 (#1394)
stoneatom/stonedb pull request #1395
Opened 2023-03-15 11:07 UTC by adofsauron

Solution: limit 0 is executed without tianmu

## Summary about this PR

Issue Number: close #1394 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2023-03-15 11:12 UTC, RingsC requested changes, later dismissed

2023-03-15 11:12 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue1394.test
> +select * from c where  exists ( select * from d where d1=1  limit 1) limit 1;
Adds some cases for join

2023-03-17 01:41 UTC, haitaoguan approved these changes

2023-03-17 01:48 UTC, konghaiya approved these changes
LGTM

2023-03-17 06:02 UTC, hustjieke approved these changes
LGTM

2023-03-17 08:48 UTC, merged