feat(stonedb) Valgrind problems(#137)(#110)(#109)(#108)(#81)(#80)(#67)(#66)(#60)
stoneatom/stonedb pull request #140
Opened 2022-07-01 03:19 UTC by konghaiya

## Summary about this PR

Issue Number: close (#137)(#110)(#109)(#108)(#81)(#80)(#67)(#66)(#60)

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [X] Bug Fix
- [X] Improvement
- [X] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-07-01 03:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stoneatom/stonedb?pullRequest=140) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stoneatom/stonedb?pullRequest=140) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stoneatom/stonedb?pullRequest=140) it.</sub>

2022-07-01 03:47 UTC, RingsC requested changes

2022-07-01 03:47 UTC, RingsC commented on storage/stonedb/system/cacheable_item.cpp
> +    filename = new char[filename_n_position + 38];  // "...path.../XXXXXXnnnnnnAAAAAAAABBBBBBBB.sdb_tmp"
do initialization after allocation

2022-07-01 03:47 UTC, RingsC commented on storage/stonedb/system/cacheable_item.cpp
> +    filename = new char[37];  // "XXXXXXnnnnnnAAAAAAAABBBBBBBB.sdb_tmp"
same as above

2022-07-01 03:47 UTC, RingsC commented on storage/stonedb/system/cacheable_item.cpp
> +    filename = new char[filename_n_position + 38];  // "...path.../XXXXXXnnnnnnAAAAAAAABBBBBBBB.sdb_tmp"
Do not use magic number

2022-07-01 03:47 UTC, RingsC commented on storage/stonedb/system/cacheable_item.cpp
> +    filename = new char[37];  // "XXXXXXnnnnnnAAAAAAAABBBBBBBB.sdb_tmp"
Do not use magic number

2022-07-01 03:47 UTC, RingsC commented on storage/stonedb/system/cacheable_item.cpp
>      std::strcpy(filename, temp_filename.c_str());
use strncpy, not this. to make it string cpy safty.

2022-07-01 09:01 UTC, hustjieke approved these changes

2022-07-02 15:39 UTC, RingsC approved these changes
LGTM

2022-07-02 15:40 UTC, merged