fix(tianmu):Resolve DDL and insert inot select Possible space inflation issues(#366)
stoneatom/stonedb pull request #1497
Opened 2023-03-30 03:26 UTC by konghaiya

## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2023-04-05 03:15 UTC, wisehead requested changes

2023-04-05 03:15 UTC, wisehead commented on storage/tianmu/core/tianmu_table.cpp
>    for (uint i = 0; i < NumOfAttrs(); i++) {
TianmuTable::Insert will be called if tianmu_sysvar_insert_delayed is OFF, and data should be inserted to disk synchronously. so using async thread to write the data is incorrect here? am i right?

2023-04-06 01:51 UTC, wisehead approved these changes

2023-04-06 01:58 UTC, haitaoguan approved these changes

2023-04-06 02:23 UTC, merged