docs(quickstart): add stonedb-8.0 compiling guide #1449
stoneatom/stonedb pull request #1514
Opened 2023-04-03 03:35 UTC by Double0101

## Summary about this PR

Issue Number: close #1449

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [x] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2023-04-03 06:26 UTC, Nliver requested changes

2023-04-03 06:26 UTC, Nliver commented on CONTRIBUTING.md
> +4.  Do *make mtr test* [How to add mtr test](./Docs/02-getting-started/quick-add-mtr-test.md)
This link should be replaced with an absolute link to the site. Relative files in the Github repository are not recommended, as the files in the Docs directory are for rendering the site.

2023-04-03 06:26 UTC, Nliver commented on Docs/02-getting-started/quick-add-mtr-test.md
StoneDB except English documents, as well as Chinese documents, corresponding Chinese document directory in this article: `stonedb/website/i18n/useful/docusaurus-plugin-content-docs/current
/02-getting-started/`

2023-04-03 06:26 UTC, Nliver commented on Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
StoneDB except English documents, as well as Chinese documents, corresponding Chinese document directory in this article: `stonedb/website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods
/compile-using-ubuntu2004/`

2023-04-03 06:26 UTC, Nliver commented on Docs/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
> +sidebar_position: 5.151
The `5.15` code here is already used in the `stonedb/Docs/04-developer-guide/00-compiling-methods/compile-using-docker.md file`. This file is compiled under Ubuntu. It is recommended that you change the number to `5.140`. 

Of course, the home directory for this number is `using-ubuntu2004`, so it's best if your build method is compatible with `ubuntu20.04` as well

2023-04-03 06:28 UTC, Nliver commented
As you know, it takes patience to update the documentation, so I have suggested some detailed changes in hopes of helping you understand StoneDB's documentation system, as well as suggesting that you update the corresponding Chinese documentation.

2023-04-10 09:10 UTC, chenshengjiang commented on website/i18n/zh/docusaurus-plugin-content-docs/current/04-developer-guide/00-compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu2204-for-80.md
> +sudo apt install -y zlib1g-dev
重复

2023-04-11 06:31 UTC, hustjieke commented on CONTRIBUTING.md
> +4.  Do *make mtr test* [How to add mtr test](https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu22.04-for-80/)
not mtr links?

2023-04-11 06:40 UTC, hustjieke approved these changes
LGTM

2023-04-11 06:41 UTC, hustjieke commented
@Nliver @haitaoguan 
Please take a CR.

2023-04-11 06:59 UTC, Nliver requested changes

2023-04-11 06:59 UTC, Nliver commented on CONTRIBUTING.md
> +4.  Do *make mtr test* [How to add mtr test](https://stonedb.io/docs/developer-guide/compiling-methods/compile-using-ubuntu2204/compile-using-ubuntu22.04-for-80/)
the link here does not point to the relevant documentation for MTR？

2023-04-11 06:59 UTC, Nliver commented on Docs/02-getting-started/quick-add-mtr-test.md
> +# Add and Run a MTR test
The first header is used to render the page title. The following code is recommended instead：
```
# Qucik Add MTR Test

## Add and Run a MTR test

### ......
```

2023-04-11 06:59 UTC, Nliver commented on website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-add-mtr-test.md
> +# 添加并运行一个mtr测试用例
The first header is used to render the page title. The following code is recommended instead：
```
# 快速添加 MTR Test

## 添加并运行一个 mtr 测试用例

### ......
```

2023-04-11 08:15 UTC, Nliver approved these changes
LGTM, Good job!

2023-04-11 08:29 UTC, haitaoguan approved these changes

2023-04-11 09:24 UTC, merged