docs(quickstart): add stonedb-8.0 compiling guide for CentOS 7.x
stoneatom/stonedb pull request #1756
Opened 2023-05-09 07:48 UTC by xxq-xu

## Summary about this PR

Issue Number: close #1753 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2023-05-09 07:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stoneatom/stonedb?pullRequest=1756) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stoneatom/stonedb?pullRequest=1756) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stoneatom/stonedb?pullRequest=1756) it.</sub>

2023-05-09 12:55 UTC, RingsC approved these changes
LTGM, thanks for your works.

2023-05-10 01:58 UTC, Nliver requested changes
I suggest that you update relevant documents in Chinese at the same time, otherwise, the Chinese page will display errors

2023-05-10 01:58 UTC, Nliver commented on Docs/04-developer-guide/00-compiling-methods/compile-using-centos7/compile-using-centos7-for-80.md
StoneDB except English documents, as well as Chinese documents, corresponding Chinese document directory in this article: `website/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/quick-deployment`

2023-05-10 01:58 UTC, Nliver commented on Docs/04-developer-guide/00-compiling-methods/compile-using-centos7/compile-using-centos7-for-80.md
I suggest that you update relevant documents in Chinese at the same time, otherwise, the Chinese page will display errors

2023-05-10 03:27 UTC, xxq-xu commented on Docs/04-developer-guide/00-compiling-methods/compile-using-centos7/compile-using-centos7-for-80.md
ok, i have updated the Chinese docs

2023-05-10 03:29 UTC, Nliver approved these changes
LGTM，good job~

2023-05-10 03:29 UTC, merged