fix(core): Added handling of CACHE_ITEM type in MysqlExpression, fix #342
stoneatom/stonedb pull request #346
Opened 2022-08-03 08:35 UTC by gougexuanli

## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-08-03 08:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stoneatom/stonedb?pullRequest=346) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stoneatom/stonedb?pullRequest=346) before we can accept your contribution.<br/><hr/>**dfx** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stoneatom/stonedb?pullRequest=346) it.</sub>

2022-08-09 07:22 UTC, RingsC requested changes
See the comments in issue

2022-08-10 05:35 UTC, RingsC approved these changes

2022-08-10 07:46 UTC, adofsauron approved these changes
LGTM

2022-08-10 08:19 UTC, merged