Bug(O&M Guide): Added extensions deccriptions in topics related to backup and recovery(#360)
stoneatom/stonedb pull request #361
Opened 2022-08-04 07:14 UTC by xuejiao-joy

## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [X] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [X] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-08-04 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stoneatom/stonedb?pullRequest=361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stoneatom/stonedb?pullRequest=361) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stoneatom/stonedb?pullRequest=361) it.</sub>

2022-08-08 02:33 UTC, RingsC requested changes
Pls, open a new issue to describe what's the problem we meet. therefore, this PR is used for.

2022-08-08 06:12 UTC, Nliver approved these changes

2022-08-10 07:53 UTC, RingsC approved these changes

2022-08-10 08:43 UTC, merged