Refactor the aggregation to multithread
stoneatom/stonedb pull request #472
Opened 2022-09-08 03:44 UTC by adofsauron

Issue Number: close #422 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-09-08 04:21 UTC, adofsauron commented
​

Abstract:

Outline the design of aggregate multithreaded parallelism



https://github.com/stoneatom/stonedb/issues/422



Demand analysis:

Functional Requirements:

Consistent with aggregation conditions handled by existing logic

The Aggregate function is used as the entry and ResultSender is used as the result output

Performance Requirements:

Table data limit:

The upper limit of a physical drive

The memory limit is exceeded. Procedure

Memory usage limit:

Add a parameter that controls the maximum amount of memory that can be used during aggregation

A temporary disk file is used if the limit is exceeded

Execution time limit:

Under the same conditions, it is in the same order of magnitude as InnoDB aggregate query at most

Aim to take less time than InnoDB for aggregated queries

Summary Feature breakdown:

Partition of table tuples:

Segmentation target:

The table data traversed by a single thread is evenly divided into different intervals, so that different worker threads can independently process a certain interval of data

Correctly handle the memory visibility of different worker threads to ensure that the function of the worker thread itself is complete and correct, and will not cause different threads to work with each other due to the overlap of critical sections

Facing Problems:

How do I get the table tuple description, how many rows, how many columns, how many packs?

What are the rules for dividing a tablespace into intervals, how many worker threads are started, and how many intervals are handled by each worker thread?

GroupByWrapper currently stores the complete information of the table and holds the identity information of whether a row of the column has a block of data, which makes it impossible for multiple threads to process the class in parallel. Whether to maintain a GroupByWrapper class in each thread to store only the information about the current tuple range, so that the worker thread can handle it independently

The GroupByWrapper class stores the information of the matching aggregation column, which is the same in each worker thread. Whether to separate the information of the aggregation column into a separate data structure, each worker thread will read only

Should we also use the current encapsulation layers of GroupByWrapper and GroupTable, GroupDistinctTable and GroupDistinctCache, and does that really cut functionality correctly? What is the maintenance cost? Is it already the optimal class organization structure?

The ValueMatchingTable class, which previously stored aggregated data, should now be replaced with a Parallel Hash Map, which would otherwise require data to be stored in each worker thread. Finally, the data in each worker thread is copied together to do a global aggregate processing operation. The performance overhead of memory copy is huge and unacceptable. How does the interface of the Parallel Hash Map class combine with the logic of the upper-level traversal aggregation when replacing a local hash?

When writing aggregate data, how does a parallel Hash map perform aggregation operation with existing data to form a unified result? How to ensure the correctness of aggregate summary results?

What are the lock rules when a parallel Hash map involves multiple threads competing to write the value of the same aggregation condition? How can I avoid overwriting the results of different worker threads?

Strip the column attributes of the processing aggregate:

Process aggregated columns whose meta-attributes are independent of a particular tuple and are invariant and can be stripped

The GroupByWrapper class retains data associated with tuples during the tuple traversal, such as rows that have been processed, data that has been aggregated, etc











​

2022-09-08 07:28 UTC, RingsC requested changes

2022-09-08 07:28 UTC, RingsC commented on .jenkins/jenkinsfile-mysql8-centos7-30-119
> +    agent {
I suggest you committing these jenkins in another independent ISSUE and PR.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/aggregation_algorithm.cpp
> -    MultiDimensionalGroupByScan(gbw, local_limit, offset, sender, limit_less_than_no_groups);
Pls, follow the commit guide. The PR title, commit message, etc.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/vc/virtual_column_base.cpp
> -  DEBUG_ASSERT(res != common::NULL_VALUE_64);
Why do you delete this line? it's a protective code.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/value_matching_table.h
> +  virtual bool FindCurrentRow(unsigned char *input_buffer, int64_t &row, bool add_if_new, int match_width) {
It's not A GOOD IDEA that adds these codes here. 
```
 37 class ValueMatchingTable {  // abstract class: interface for value matching
 38                             // (Group By etc.)

```
and, what's the meaning of your input params, `match_width` ?

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/value_matching_table.h
> +  virtual bool FindCurrentRow(unsigned char *input_buffer, int64_t &row, bool add_if_new, int match_width) {
BTW: your  can make this function to be  readability.
```
 int64_t NoRows() { return int64_t(no_rows); }  // rows stored so far
        ..
 virtual bool NoMoreSpace() = 0;                // hard stop: any new value will be rejected
```

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/value_matching_table.cpp
> +#if 0
If these codes are useless, pls, remove it now, not just comment it out.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/value_matching_hashtable.cpp
> +bool ValueMatching_HashTable::FindCurrentRow(unsigned char *input_buffer, int64_t &row, bool add_if_new,
All new added codes should pass clang-format checking.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/rc_attr.h
> +  Pack *GetPack(int64_t obj) {
The `obj` is what? and if we can foud or some errors occur, what's value of `pack` ?

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/aggregation_algorithm.cpp
> +  auto get_thd_cnt = []() {
Why 4? not 5 or somthing else.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/aggregation_algorithm.cpp
> +  auto get_thd_cnt = []() {
and I think that you miss these 
```
if (ParallelAllowed(gbw) && !limit_less_than_no_groups) {
    thd_cnt = std::thread::hardware_concurrency() / 4; // For concurrence reason, don't swallow all
}
```
the original one has been stated the condition of parallelization.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/aggregation_algorithm.cpp
> +  if (force_parall) {
I thik we can refine these comparsion statement to be more concise.

2022-09-08 07:28 UTC, RingsC commented on storage/tianmu/core/aggregation_algorithm.cpp
> +    } while (gbw.AnyTuplesLeft() && (1 == thd_cnt));  // do the next pass, if anything left
thd_cnt will update its value in every `while loop` or not?  which statement does update the value of `thd_cnt`?

2022-09-14 07:24 UTC, adofsauron commented on storage/tianmu/vc/virtual_column_base.cpp
> -  DEBUG_ASSERT(res != common::NULL_VALUE_64);
If do not do this, Q16 will not be executed

2022-09-14 07:35 UTC, adofsauron commented on storage/tianmu/core/value_matching_table.h
> +  virtual bool FindCurrentRow(unsigned char *input_buffer, int64_t &row, bool add_if_new, int match_width) {
In the subclass ValueMatching_HashTable, used to compare the lengths of matching strings

2022-09-14 09:42 UTC, adofsauron commented on storage/tianmu/core/aggregation_algorithm.cpp
> +    } while (gbw.AnyTuplesLeft() && (1 == thd_cnt));  // do the next pass, if anything left
no, never after be set value over

2022-09-14 09:43 UTC, adofsauron commented on storage/tianmu/core/aggregation_algorithm.cpp
> +  if (force_parall) {
yes, let me think about a minutes

2022-09-15 02:54 UTC, adofsauron commented on storage/tianmu/core/rc_attr.h
> +  Pack *GetPack(int64_t obj) {
no more use this code, to delete

2022-09-15 02:54 UTC, adofsauron commented on storage/tianmu/core/value_matching_hashtable.cpp
> +bool ValueMatching_HashTable::FindCurrentRow(unsigned char *input_buffer, int64_t &row, bool add_if_new,
that's great

2022-09-15 02:55 UTC, adofsauron commented on storage/tianmu/core/value_matching_table.cpp
> +#if 0
It is better to leave it, now that the entire code logic does not cover all the details, and to add a parameter control

2022-09-15 02:57 UTC, adofsauron commented on storage/tianmu/core/value_matching_table.h
> +  virtual bool FindCurrentRow(unsigned char *input_buffer, int64_t &row, bool add_if_new, int match_width) {
> 

It's better to keep readability and functional logic separate, or else the code that goes wrong and needs to be rolled back will be too big

2022-09-16 06:45 UTC, isredstar approved these changes
Nice job， but we hope from now on there will be stronger code for the multithread query processing.

2022-09-16 08:49 UTC, hustjieke approved these changes
LGTM

2022-09-17 08:19 UTC, merged