feat(StoneDB 8.0): parent_lex->result is nullptr in "select ... from" clause without "into outfile/dumpfile". (#557)
stoneatom/stonedb pull request #572
Opened 2022-09-26 08:58 UTC by lujiashun

[summary]
1 "SELECT ... INTO OUTFILE/DUMPFILE",parent_lex->result is not nullptr;
 2 "SELECT ... FORM ",normal clause,parent_lex->result is nullptr; 
3 parent_lex->result can be used to check the dumpfile,just to check null value;

## Summary about this PR

Issue Number: close #557
```
 auto exchange =
      static_cast<Query_result_to_file *>(selects_list->parent_lex->result)->get_sql_exchange();
  if (exchange) {
    is_dumpfile = exchange->dumpfile;
    return exchange->file_name;
  }
```
1 "SELECT ... INTO OUTFILE/DUMPFILE",parent_lex->result is not nullptr;
 2 "SELECT ... FORM ",normal clause,parent_lex->result is nullptr; 
3 parent_lex->result can be used to check the dumpfile,just to check null value;

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [X] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-09-26 15:29 UTC, RingsC requested changes

2022-09-26 15:29 UTC, RingsC commented on storage/tianmu/core/engine.cpp
>    // stonedb8 start
It's ok for commit after removing the `stonedb` comments.

2022-09-27 01:50 UTC, RingsC approved these changes
LGTM

2022-09-27 01:53 UTC, DandreChen approved these changes
LGTM

2022-09-27 01:53 UTC, merged