feat(StoneDB 8.0): thd->no_errors no_errors is deleted. (#574)
stoneatom/stonedb pull request #575
Opened 2022-09-26 12:07 UTC by lujiashun

[summary]
1 no_erros is used little in mysql5.7，eg in Item::update_null_value and so on. 
2 code is refacted in 8.0,and use push_warning or my_error function to mark errors in is_error function.

Reference: https://github.com/mysql/mysql-server/commit/9fce6b0f909b09645d308912001c4234e06eaf3a
      in the mysql commit, we can see that is_errors is deleted directly almost. But check the code, like the
      the items related function, push_warning|my_error is used to mark errors. So use is_error is a better solution.

## Summary about this PR

Issue Number: close #574 
fix: thd->no_errors no_errors is deleted.
the no_erros is used little in mysql5.7，eg in Item::update_null_value and so on. In mysql8.0,
the code is refacted,and is used push_warning or my_error function to mark erros in is_error function.
The solution is to use is_erro instead no_errors.

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [X] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-09-26 14:58 UTC, RingsC approved these changes
see the comment.

2022-09-26 14:59 UTC, RingsC requested changes

2022-09-26 14:59 UTC, RingsC commented on storage/tianmu/handler/tianmu_handler_com.cpp
> +  if (!( thd->is_error() || thd->killed || thd->transaction_rollback_request)) { // stonedb8
remove the `stonedb8`.

2022-09-27 01:51 UTC, RingsC approved these changes
LGTM

2022-09-27 01:54 UTC, DandreChen approved these changes
LGTM

2022-09-27 01:57 UTC, merged