fix(tianmu): date functions are used in the where statement, query result is empty.(#566) (#279)
stoneatom/stonedb pull request #601
Opened 2022-09-28 09:13 UTC by gougexuanli

## Summary about this PR

Issue Number: close #566 #279

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-09-29 08:46 UTC, isredstar approved these changes
LGTM

2022-09-30 01:30 UTC, hustjieke commented on storage/tianmu/types/rc_datetime.cpp
> -  ASSERT(at == common::CT::DATETIME || at == common::CT::TIMESTAMP,
"should be 'at == common::CT::DATETIME || at == common::CT::TIMESTAMP'");
---》
"should be 'at == common::CT::DATETIME || at == common::CT::TIMESTAMP || common::CT::DATE'");

2022-10-11 11:53 UTC, gougexuanli commented on storage/tianmu/types/rc_datetime.cpp
> -  ASSERT(at == common::CT::DATETIME || at == common::CT::TIMESTAMP,
ok, already modified

2022-10-13 05:50 UTC, RingsC requested changes

2022-10-13 05:50 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue_566.test
> +USE test;
To include `have_tianmu.inc`  at first

2022-10-13 06:03 UTC, gougexuanli commented on mysql-test/suite/tianmu/t/issue_566.test
> +USE test;
ok

2022-10-13 08:25 UTC, hustjieke approved these changes
LGTM

2022-10-13 08:26 UTC, merged