fix(tianmu) Explain select straight_join DISTINCT.The rows in the test result is incorrect (#270)
stoneatom/stonedb pull request #684
Opened 2022-10-11 01:46 UTC by konghaiya

fix(tianmu) Explain select straight_join DISTINCT.The rows in the test result is incorrect (#270)

Cause of the problem:
In the mode where the type is ref, the line number returned by the tianmu engine is 10 by default. 
Modify Scheme:
Delete the logic that returns 10 rows by default, and return the number of rows in the table instead.

## Summary about this PR

Issue Number: close #270

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-12 07:41 UTC, RingsC requested changes

2022-10-12 07:41 UTC, RingsC commented on mysql-test/suite/tianmu/r/issue270.result
> +# Explain select straight_join DISTINCT.The rows in the test result is incorrect (#270)
disable the warnings, Do we use the warnings to test something?

2022-10-13 03:46 UTC, isredstar approved these changes

2022-10-13 05:48 UTC, RingsC approved these changes
LGTM

2022-10-13 05:56 UTC, merged