fix(Tianmu) Fix assertion errors caused by syntax optimization of the tianmu engine (#669)
stoneatom/stonedb pull request #694
Opened 2022-10-11 12:14 UTC by konghaiya

Fix assertion errors caused by syntax optimization of the tianmu engine (#669)

Cause of the problem:
The tianmu engine created join objects in syntax optimization, but did not explain them 
Modify Scheme:
Release the join object after use

## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-12 12:27 UTC, RingsC requested changes

2022-10-12 12:27 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue669.test
> +--echo # Release the join object after use
Remove these comments, uncessary.

2022-10-12 12:27 UTC, RingsC commented on storage/tianmu/core/query_compile.cpp
> +      sl->join = NULL;
using nullptr, not NULL

2022-10-12 13:12 UTC, RingsC requested changes

2022-10-12 13:12 UTC, RingsC commented on storage/tianmu/core/query_compile.cpp
> +    ORDER *group = sl->group_list.first;
why NULL is still here.

2022-10-13 05:47 UTC, RingsC approved these changes
LGTM

2022-10-13 06:18 UTC, hustjieke commented on storage/tianmu/core/query_compile.cpp
> +      isNewJon = true;
What is var `isNewJon` mean?  ---> `isNewJoin`?
Add comment to desc this var.
or use `ifNewJoinForTianmu` ?

2022-10-13 08:28 UTC, hustjieke approved these changes
LGTM

2022-10-13 09:10 UTC, merged