feat(StoneDB 8.0): sql command "show status" support "tianmu status v…ariables". (#703)
stoneatom/stonedb pull request #704
Opened 2022-10-12 07:12 UTC by lujiashun

[summary]
1 change tianmu status var scope from SHOW_SCOPE_UNDEF to SHOW_SCOPE_GLOBAL;

## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-12 07:58 UTC, DandreChen approved these changes
LGTM

2022-10-12 08:09 UTC, RingsC requested changes

2022-10-12 08:09 UTC, RingsC commented on storage/tianmu/handler/ha_rcengine.cpp
> +  { "Tianmu_" #label, (char *)get_##name##_StatusVar, SHOW_FUNC, SHOW_SCOPE_GLOBAL }
A test case is need.

2022-10-13 05:46 UTC, RingsC approved these changes

2022-10-13 05:53 UTC, hustjieke approved these changes
LGTM

2022-10-13 09:03 UTC, merged