feat(StoneDB 8.0): insert DML bin log events should be ignored. (#723)
stoneatom/stonedb pull request #729
Opened 2022-10-17 03:17 UTC by lujiashun

## Summary about this PR

Issue Number: close #723

[summary]
1 insert DML binlog log will be convert to "load into outfile ..." with other insert DMLs;

## Tests Check List

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [x] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-17 03:28 UTC, DandreChen approved these changes
LGTM.

2022-10-17 06:40 UTC, RingsC requested changes

2022-10-17 06:40 UTC, RingsC commented on sql/sql_insert.cc
> +      if (mysql_bin_log.is_open()&& !tianmu_engine) {
I think that should be like this: do tianmu check firstly, then binlog flag check. 
if (!tianmu_engine && mysql_bin_log.is_open())

2022-10-17 07:57 UTC, RingsC approved these changes

2022-10-17 13:11 UTC, DandreChen approved these changes
LGTM.

2022-10-18 01:40 UTC, RingsC approved these changes
LGTM

2022-10-18 01:59 UTC, hustjieke approved these changes
LGTM

2022-10-18 02:18 UTC, merged