fix(tianmu)Fix delete from Multiple-Table, Failed to delete the data (#663)
stoneatom/stonedb pull request #746
Opened 2022-10-18 12:12 UTC by konghaiya

fix(tianmu)Fix delete from Multiple-Table, Failed to delete the data (#663)(#678)
Cause:
At present, the primary key of the tianmu engine does not fully support delete and update statements. 
Temporary solution:
Modify the execution plan of the SQL layer so that the delete and update statements do not follow the primary key logic

fix issue: 
- #663 
- #678

## Summary about this PR

Issue Number: close #663 , #678

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-19 03:30 UTC, isredstar commented
Will the solution affect other queries？ @konghaiya

2022-10-19 03:35 UTC, konghaiya commented
The query will not be affected. The modifications here limit the delete and update statements of tianmu.

2022-10-19 07:50 UTC, RingsC requested changes

2022-10-19 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/r/delete.result
>  select * from t12;
The PR title format

2022-10-19 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue663.test
> +--echo #
delete unrelated comment messages

2022-10-19 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue663.test
> +delete t2.*,t3.* from t1,t2,t3 where t1.a=t2.a AND t2.b=t3.a and t1.b=t3.b;
Addings more `where` conditions, such as combinations conditions.

2022-10-19 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue663.test
> +select * from t1;
`select` statement should be test  with differ selection conditions.

2022-10-19 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue663.test
> +select * from t3;
And tests for query plan should be existed.

2022-10-19 07:50 UTC, RingsC commented on sql/sql_planner.cc
> +  bool tianmuDeleteOrUpdate = (tianmu_engine && (sqlCommand == SQLCOM_DELETE ||
I think this logic is better in optimization. in optimization, if we foud the table is Tianmu table. we disable the `key` information. 

Then, here, tab->keyuse() of a Tianmu table is in disable status.

2022-10-20 06:03 UTC, RingsC requested changes

2022-10-20 06:03 UTC, RingsC commented on sql/sql_optimizer.cc
> +    TABLE *const table= join_tab->table();
Adds table is a inullptr or not check.

2022-10-20 07:10 UTC, isredstar commented on sql/sql_optimizer.cc
> +    TABLE *const table= join_tab->table();
It is necessary @konghaiya

2022-10-20 07:14 UTC, konghaiya commented on sql/sql_optimizer.cc
> +    TABLE *const table= join_tab->table();
Code for nullptr check has been added

2022-10-20 07:14 UTC, RingsC approved these changes
LGTM

2022-10-20 07:26 UTC, isredstar approved these changes

2022-10-20 07:34 UTC, merged

2022-10-20 07:40 UTC, RingsC commented
Now, tianmu, is not support PK very well, we will improve to support PK in future. And, that time, we will remove this optimization restriction.