fix(core): fix the bug of incorrect result set of count function (#736)
stoneatom/stonedb pull request #756
Opened 2022-10-19 12:43 UTC by lylth

Replace the function FindCurrentRowByVMTable that gets the current row to FindCurrentRow.

## Summary about this PR

Issue Number: close #736 
fix(core): fix the bug of incorrect result set of count function (#736)
         Replace the function FindCurrentRowByVMTable that gets the current row to FindCurrentRow.

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-19 13:27 UTC, RingsC commented
@lylth  Ref : https://github.com/stoneatom/stonedb/pull/472. Changes in thsi PR.

2022-10-20 06:19 UTC, isredstar approved these changes
LGTM

2022-10-20 08:37 UTC, RingsC requested changes

2022-10-20 08:37 UTC, RingsC commented on storage/tianmu/core/group_distinct_table.cpp
>    if (max_bytes > 2000000000)  // possible for large aggregation settings, but
using : 2 * 1024*1024, instead of 2000000000.

2022-10-20 08:37 UTC, RingsC commented on storage/tianmu/core/group_distinct_table.cpp
>    t = (unsigned char *)alloc(total_width * no_rows, mm::BLOCK_TYPE::BLOCK_TEMPORARY);
using c++ style type cast.

2022-10-20 08:37 UTC, RingsC commented on storage/tianmu/core/group_distinct_table.cpp
>    input_buffer = (unsigned char *)(new int[total_width / 4 + 1]);  // ensure proper memory alignment
c++ style type cast.

2022-10-20 08:37 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue736.test
> +INSERT INTO t1 VALUES(NULL,''),(1,'a'),(1,'b'),(1,'c'),(2,'dd'),(3,'eee');
Add some tests for unicode charset.

2022-10-21 01:37 UTC, RingsC requested changes

2022-10-21 01:37 UTC, RingsC commented on storage/tianmu/core/group_distinct_table.cpp
> +  t = reinterpret_cast<unsigned char *>(alloc(total_width * no_rows, mm::BLOCK_TYPE::BLOCK_TEMPORARY));
Use static_cast, not reinterpret_cast, 
Ref: https://en.cppreference.com/w/cpp/language/reinterpret_cast
        https://en.cppreference.com/w/cpp/language/static_cast

2022-10-21 02:36 UTC, RingsC requested changes

2022-10-21 02:36 UTC, RingsC commented on storage/tianmu/core/group_distinct_table.cpp
> +  t = static_cast<unsigned char *>(alloc(total_width * no_rows, mm::BLOCK_TYPE::BLOCK_TEMPORARY));
to set  initial memory, set to 0x0.

2022-10-21 02:36 UTC, RingsC commented on storage/tianmu/core/group_distinct_table.cpp
> +  input_buffer = reinterpret_cast<unsigned char *>(new int[total_width / 4 + 1]);  // ensure proper memory alignment
Same thing.

2022-10-21 04:27 UTC, RingsC approved these changes

2022-10-21 06:09 UTC, merged