fix(tianmu): fix bug:'on duplicate key update' scenario, incorrect result occurs. (#502)
stoneatom/stonedb pull request #765
Opened 2022-10-20 11:44 UTC by lujiashun

## Summary about this PR

Issue Number: close #502

[summary]
1 the root reason is because of the variable ‘tianmu_insert_delayed’,set it off; 2 in debug version, it crashes, fix it;
3 add mtr case for this issue;

## Tests Check List

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [X] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-20 12:29 UTC, RingsC requested changes

2022-10-20 12:29 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue502-2.test
> +create database test_tmp;
Pls, using source to include have_tianmu.inc in. Thanks.

2022-10-20 12:29 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue502-2.test
> +create database test_tmp;
And, adds tests for string and unicode string.

2022-10-21 09:05 UTC, RingsC approved these changes
LGTM

2022-10-21 10:58 UTC, isredstar approved these changes
LGTM

2022-10-21 11:06 UTC, merged