feat(StoneDB 8.0): adapt testcase insert_select.test. (#777)
stoneatom/stonedb pull request #799
Opened 2022-10-25 08:09 UTC by lujiashun

## Summary about this PR

Issue Number: close #777

1 fix debug version crash issue;
2 compared with stonedb5.7 flow, add prepare_for_positional_update in Query_result_insert::prepare;

## Tests Check List

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [X] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-26 02:00 UTC, DandreChen approved these changes
LGTM.

2022-10-27 01:29 UTC, RingsC requested changes

2022-10-27 01:29 UTC, RingsC commented on mysql-test/suite/tianmu/t/flow_control_function.test
>  --echo #
Suggestion: remove these comments. It's redundent, the file name indicates what we do in this test.

2022-10-27 01:29 UTC, RingsC commented on mysql-test/suite/tianmu/t/flow_control_function.test
>  --echo #
```
--echo #
--echo # Flow control function,Based on the test
--echo #
```

2022-10-27 01:29 UTC, RingsC commented on sql/sql_insert.cc
> +  // tianmu start, TODO, refer to stonedb5.7 implementation
Remove the useless comment, we have git log to trance the changes.

2022-10-27 02:27 UTC, RingsC approved these changes
LGTM, Great Job

2022-10-27 02:47 UTC, merged