feat(tianmu): Supports user-defined functions (#538)
stoneatom/stonedb pull request #835
Opened 2022-10-27 15:34 UTC by adofsauron

Requirement analysis:
    https://adofsauron.blog.csdn.net/article/details/126991367

    Changes description:
    https://blog.csdn.net/adofsauron/article/details/127543458

## Summary about this PR

Issue Number: close #538 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [x] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-28 07:50 UTC, RingsC requested changes

2022-10-28 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/r/custom_function.result
> +use test;
using "--source have_tianmu.inc"

2022-10-28 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/r/custom_function.result
> +use test;
using --disable_query_log/ --enable_query_log to shut down the unused log.

2022-10-28 07:50 UTC, RingsC commented on mysql-test/suite/tianmu/r/custom_function.result
> +use test;
the file name should be attached to an issue.

2022-11-01 05:43 UTC, RingsC requested changes

2022-11-01 05:43 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue538.test
> +--disable_warnings
Why do u use disable warnings twice?

2022-11-01 05:43 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue538.test
> +SELECT get_value(1);
I think we need these test.  Taking an instance: 
select sum (xx + get_value(1)) xxx
or 
select xxx from xxx where xxx oper get_value. 
....
etc.

2022-11-01 12:07 UTC, adofsauron commented on mysql-test/suite/tianmu/t/issue538.test
> +SELECT get_value(1);
sure, wait a time for add this

2022-11-01 13:47 UTC, closed without merging