feat(tianmu):Improve the readbility of stonedb.(#11)
stoneatom/stonedb pull request #839
Opened 2022-10-28 04:23 UTC by DandreChen

## Summary about this PR

Issue Number: close #11 

[summary]
class member variable refactor：handler directory

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [x] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-28 07:54 UTC, RingsC requested changes

2022-10-28 07:54 UTC, RingsC commented on storage/tianmu/handler/ha_rcengine.cpp
> +  char tianmu_msg[256];
the variables should be initialized.

2022-10-28 08:14 UTC, DandreChen commented on storage/tianmu/handler/ha_rcengine.cpp
> +  char tianmu_msg[256];
fixed it

2022-10-28 08:24 UTC, RingsC requested changes

2022-10-28 08:24 UTC, RingsC commented on storage/tianmu/handler/ha_rcengine.cpp
>    int tianmu_errcode;
How about this `tianmu_errcode` ?

2022-10-28 08:45 UTC, RingsC requested changes

2022-10-28 08:45 UTC, RingsC commented on storage/tianmu/handler/tianmu_handler.cpp
> +    table_ptr_ = NULL;
recommend: nullptr.

2022-10-28 08:45 UTC, RingsC commented on storage/tianmu/handler/tianmu_handler.h
> +  uint dupkey_pos_ = -1;
assign negtive integer to an unsigned int may lead turn-flip. Becare about the symbol flag.

2022-10-28 08:45 UTC, RingsC commented on storage/tianmu/handler/tianmu_handler.h
> +  std::unique_ptr<core::Filter> filter_ptr_;
All these variable should have an initial value.

2022-10-29 15:27 UTC, DandreChen commented on storage/tianmu/handler/ha_rcengine.cpp
>    int tianmu_errcode;
fixed it

2022-10-30 08:41 UTC, RingsC approved these changes
LGTM

2022-10-30 08:53 UTC, lujiashun approved these changes
LGTM

2022-10-30 08:53 UTC, merged