feat(tianmu): Improve the readbility of stonedb. (#11)
stoneatom/stonedb pull request #853
Opened 2022-10-31 08:48 UTC by lylth

[summary]
    1.class member variable refactor：common directory

## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-10-31 09:12 UTC, RingsC requested changes

2022-10-31 09:12 UTC, RingsC commented on storage/tianmu/common/exception.h
> +  ErrorCode ec_;
using `err_code_`, not just with underscore。 this pr main goal is to improve the code readibity. not just add some underscores.

2022-10-31 09:12 UTC, RingsC commented on storage/tianmu/common/data_format.h
> +  DataFormat(std::string name, EDF edf) : name(name), id(no_formats_++), edf(edf) {}
no_format is `no forma`t or `num_of_format`.

2022-10-31 09:12 UTC, RingsC commented on storage/tianmu/common/data_format.cpp
> +  auto it = df_map_.find(boost::trim_copy(boost::to_upper_copy(name)));
`df_map` is a map for what? the readers can understand the basic idea of the code via the literal words.

2022-11-01 09:22 UTC, hustjieke approved these changes
LGTM

2022-11-01 11:45 UTC, RingsC approved these changes

2022-11-02 01:46 UTC, closed without merging