feat(tianmu): fix invalid write/read issue. (#817)
stoneatom/stonedb pull request #902
Opened 2022-11-08 12:04 UTC by lujiashun

## Summary about this PR

Issue Number: ref #issue_number_you_created817

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [x] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-11-09 02:04 UTC, RingsC requested changes

2022-11-09 02:04 UTC, RingsC commented on storage/tianmu/system/cacheable_item.cpp
> +    filename = new char[filename_n_position + 37 + 4];  // "...path.../XXXXXXnnnnnnAAAAAAAABBBBBBBB.tianmu_tmp"
Pls, would you like use cosntexpr or meaningful words to describe these magic numbers?

2022-11-09 02:04 UTC, RingsC commented on storage/tianmu/core/engine_results.cpp
> +  buf_lens = new uint[fields.size()];
If we do `memset` after a new memory allocated that would be a good thing.

2022-11-10 05:43 UTC, RingsC approved these changes
LGTM

2022-11-10 07:43 UTC, hustjieke requested changes

2022-11-10 07:43 UTC, hustjieke commented on storage/tianmu/system/cacheable_item.cpp
> +  constexpr size_t MIN_OWN_NAME_LEN = 3;
The `constant names` should follow:
https://google.github.io/styleguide/cppguide.html#Constant_Names

2022-11-10 07:43 UTC, hustjieke commented on storage/tianmu/system/cacheable_item.cpp
> +  max_file_id_ = 0;
These class variables can be inited during definition in class. Follow c++11 std.
https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

2022-11-10 09:25 UTC, hustjieke approved these changes
LGTM

2022-11-10 09:54 UTC, merged