feat(stonedb): support exists/in subquery convert to semi-join (#864)
stoneatom/stonedb pull request #907
Opened 2022-11-09 07:00 UTC by duanfuxiang0

## Summary about this PR

Issue Number: close #864 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-11-10 15:07 UTC, RingsC requested changes
Pls, adds the test cases firstly to make sure we have cover all corner cases.

2022-11-10 15:07 UTC, RingsC commented on mysql-test/suite/tianmu/r/select_expressions.result
>  SELECT CASE t1_int WHEN t1_int=1 THEN t1_char ELSE t1_int END FROM t1;
such these test cases should be added .
```
1. IN/=ANY predicates on the form:

  @code
  SELECT ...
  FROM ot1 ... otN
  WHERE (oe1, ... oeM) IN (SELECT ie1, ..., ieM
                           FROM it1 ... itK
                          [WHERE inner-cond])
   [AND outer-cond]
  [GROUP BY ...] [HAVING ...] [ORDER BY ...]
  @endcode

  are transformed into:

  @code
  SELECT ...
  FROM (ot1 ... otN) SJ (it1 ... itK)
                     ON (oe1, ... oeM) = (ie1, ..., ieM)
                        [AND inner-cond]
  [WHERE outer-cond]
  [GROUP BY ...] [HAVING ...] [ORDER BY ...]
  @endcode

  Notice that the inner-cond may contain correlated and non-correlated
  expressions. Further transformations will analyze and break up such
  expressions.

  2. EXISTS predicates on the form:

  @code
  SELECT ...
  FROM ot1 ... otN
  WHERE EXISTS (SELECT expressions
                FROM it1 ... itK
                [WHERE inner-cond])
   [AND outer-cond]
  [GROUP BY ...] [HAVING ...] [ORDER BY ...]
  @endcode

  are transformed into:

  @code
  SELECT ...
  FROM (ot1 ... otN) SJ (it1 ... itK)
                     [ON inner-cond]
  [WHERE outer-cond]
  [GROUP BY ...] [HAVING ...] [ORDER BY ...]
  @endcode

  3. Negated EXISTS predicates on the form:

  @code
  SELECT ...
  FROM ot1 ... otN
  WHERE NOT EXISTS (SELECT expressions
                FROM it1 ... itK
                [WHERE inner-cond])
   [AND outer-cond]
  [GROUP BY ...] [HAVING ...] [ORDER BY ...]
  @endcode
```

2022-11-10 15:07 UTC, RingsC commented on sql/sql_resolver.cc
> +  for (TABLE_LIST*p_table_list = parent_tables.first; p_table_list;
Add a space between `TABLE_LIST*` and `p_table_list`

2022-11-10 15:07 UTC, RingsC commented on sql/sql_resolver.cc
> +  for (TABLE_LIST*p_table_list = parent_tables.first; p_table_list;
Do we just to set the flag to true ONLY via one tianmu table with PK?

2022-11-15 08:53 UTC, duanfuxiang0 commented on sql/sql_resolver.cc
> +  for (TABLE_LIST*p_table_list = parent_tables.first; p_table_list;
No need, it will automatically determine whether the tianmu's table contains a primary key

2022-11-15 08:53 UTC, duanfuxiang0 commented on mysql-test/suite/tianmu/r/select_expressions.result
>  SELECT CASE t1_int WHEN t1_int=1 THEN t1_char ELSE t1_int END FROM t1;
ok

2022-12-05 08:55 UTC, RingsC approved these changes

2023-01-30 07:33 UTC, isredstar approved these changes
LGTM

2023-02-22 07:50 UTC, closed without merging