fix(tianmu): fix query syntax (WHERE NOT IN ) is not supported. (#767)
stoneatom/stonedb pull request #910
Opened 2022-11-09 11:21 UTC by lujiashun

## Summary about this PR

Issue Number: ref #767
[summary]
1 root cause: sub-select item is the left argument,not the right argument of item_func;

## Tests Check List

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [X] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-11-14 12:00 UTC, RingsC requested changes

2022-11-14 12:00 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue767.test
> +insert into tt values (12);
it's better to adds some dependent and independent subquery cases for `NOT IN`

2022-11-14 12:00 UTC, RingsC commented on storage/tianmu/core/query.cpp
> +    left_ref = ((Item_func *)cond_removed)->arguments()[0];
Using c++ style type casting and `down_cast` would be a good choice.

2022-11-15 03:40 UTC, lujiashun commented
The sql "in" clause is not support，Its data structure is different from ”not in“ clause. Deal it later.
```
use test;
drop table if exist t1;
create table t1(val int) ENGINE=tianmu;
insert into t1 values(12);
select * from t1 where 42  in (select * from t1 where val > 42);
```

2022-11-17 01:38 UTC, RingsC approved these changes
LGTM, Great job.

2022-11-17 02:39 UTC, hustjieke approved these changes
LGTM

2022-11-17 06:27 UTC, merged