fix(tianmu): fix crashed when the subquery includes a SORT clause (#906)
stoneatom/stonedb pull request #931
Opened 2022-11-14 12:46 UTC by adofsauron

```
    fix(tianmu): fix crashed when the subquery includes a SORT clause (#906)
    the reason is The subquery generates a temp table, 
    but the count(*) column of the subquery is not a physical column, 
    so the interface is incompatible.
    so if the virtual column does not point to the physical column, 
    the check is not performed
```

## Summary about this PR

Issue Number: close #906 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-11-14 13:55 UTC, RingsC requested changes

2022-11-14 13:55 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue906.test
> +
source `include/have_tianmu.inc`

2022-11-14 13:55 UTC, RingsC commented on mysql-test/suite/tianmu/t/issue906.test
> +UNION
add cases for `union all`.

2022-11-14 13:55 UTC, RingsC commented on storage/tianmu/core/temp_table.h
> +    bool ShouldOutput() const { return IsListField() && alias; }
Uses `Short-circuit evaluation`. `alias && xxx`

2022-11-15 12:30 UTC, RingsC approved these changes
LGTM

2022-11-16 02:06 UTC, hustjieke approved these changes
LGTM

2022-11-16 02:07 UTC, merged