workflow(mergify):add perf label and PR_perf rule
stoneatom/stonedb pull request #955
Opened 2022-11-17 05:43 UTC by zsp108

## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [x] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

2022-11-17 06:59 UTC, RingsC approved these changes

2022-11-21 07:31 UTC, hustjieke requested changes

2022-11-21 07:31 UTC, hustjieke commented on .github/pull_request_template.md
> -- [ ] Improvement
The performance improvement has been existed, do not modify improvement.

2022-11-21 08:23 UTC, hustjieke approved these changes
LGTM

2022-11-22 02:28 UTC, merged